// Pure, framework-free HTTP status code reference data. Tool-specific.
//
// Sources: RFC 9110 (HTTP Semantics), RFC 6585 (Additional HTTP Status
// Codes), RFC 7538 (308), RFC 8297 (103 Early Hints), RFC 4918 (WebDAV),
// RFC 5842 (WebDAV Binding Extensions — 208/508), RFC 8470 (425 Too Early),
// RFC 7725 (451), RFC 3229 (226 IM Used), RFC 2295 (506), RFC 2774 (510).
// The "unofficial" entries are not in the IANA HTTP Status Code Registry —
// they're vendor/framework conventions (Cloudflare, nginx, Laravel, the
// legacy Twitter API) documented here because they show up in the wild.

export type StatusClass = '1xx' | '2xx' | '3xx' | '4xx' | '5xx';

/** Whether it's generally safe/useful to retry the same request. */
export type Retryable = 'yes' | 'no' | 'depends';

export interface StatusCodeEntry {
  code: number;
  reason: string;
  statusClass: StatusClass;
  /** False for vendor/framework conventions not in the IANA registry. */
  official: boolean;
  /** One or two sentence explanation of what the code means. */
  summary: string;
  /** When to use it (server-side) or what commonly causes it (client-side). */
  causes: string;
  /** Spec reference, e.g. "RFC 9110 §15.5.5". */
  spec: string;
  retryable: Retryable;
  /** Extra detail on retry semantics, shown alongside the retryable badge. */
  retryNote?: string;
  /** Whether RFC 9110 §15.1 lists this code as cacheable by default (heuristic caching allowed with no explicit cache-control). */
  cacheableByDefault: boolean;
  /** HTTP headers commonly associated with this response. */
  relatedHeaders: string[];
}

function classOf(code: number): StatusClass {
  if (code < 200) return '1xx';
  if (code < 300) return '2xx';
  if (code < 400) return '3xx';
  if (code < 500) return '4xx';
  return '5xx';
}

interface RawEntry {
  code: number;
  reason: string;
  official: boolean;
  summary: string;
  causes: string;
  spec: string;
  retryable: Retryable;
  retryNote?: string;
  cacheableByDefault: boolean;
  relatedHeaders: string[];
}

const RAW_ENTRIES: RawEntry[] = [
  // ---------------------------------------------------------------- 1xx --
  {
    code: 100,
    reason: 'Continue',
    official: true,
    summary:
      "The initial part of the request has been received and hasn't been rejected; the client should continue sending the request body.",
    causes:
      'Sent by the server in response to a request carrying an `Expect: 100-continue` header, before the client uploads a (possibly large) body, so the client can avoid sending a body that would be rejected.',
    spec: 'RFC 9110 §15.2.1',
    retryable: 'no',
    retryNote: 'Interim response — not a final outcome, nothing to retry.',
    cacheableByDefault: false,
    relatedHeaders: ['Expect'],
  },
  {
    code: 101,
    reason: 'Switching Protocols',
    official: true,
    summary:
      "The server agrees to switch to the protocol requested by the client's `Upgrade` header.",
    causes:
      'Sent right before the connection switches protocols, e.g. upgrading an HTTP connection to a WebSocket.',
    spec: 'RFC 9110 §15.2.2',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Upgrade', 'Connection'],
  },
  {
    code: 102,
    reason: 'Processing',
    official: true,
    summary:
      "The server accepted the request but hasn't finished processing it; sent so the client doesn't assume a timeout.",
    causes:
      'Used by WebDAV for operations (e.g. COPY/MOVE of large collections) that take longer than a single response round trip.',
    spec: 'RFC 4918 §10.1',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 103,
    reason: 'Early Hints',
    official: true,
    summary:
      "Sent before the final response so the client can start acting on some headers (e.g. preloading resources) early.",
    causes:
      'The server knows some response headers (typically `Link` preload/preconnect hints) before it has finished computing the full response.',
    spec: 'RFC 8297 §2',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Link'],
  },

  // ---------------------------------------------------------------- 2xx --
  {
    code: 200,
    reason: 'OK',
    official: true,
    summary: 'The request succeeded, and the response body contains the requested representation.',
    causes: 'The standard success response for GET, POST, PUT, etc. when there is a body to return.',
    spec: 'RFC 9110 §15.3.1',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['ETag', 'Last-Modified', 'Cache-Control'],
  },
  {
    code: 201,
    reason: 'Created',
    official: true,
    summary: 'The request succeeded and resulted in a new resource being created.',
    causes:
      'Typical response to a successful POST (or a PUT that creates a resource); `Location` should point at the new resource.',
    spec: 'RFC 9110 §15.3.2',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 202,
    reason: 'Accepted',
    official: true,
    summary: 'The request has been accepted for processing, but processing is not yet complete.',
    causes:
      'Asynchronous/background processing where the final outcome is unknown yet; clients often poll a status resource.',
    spec: 'RFC 9110 §15.3.3',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 203,
    reason: 'Non-Authoritative Information',
    official: true,
    summary:
      "The returned metadata isn't exactly what the origin server would have returned, typically because an intermediary modified it.",
    causes: 'A transforming proxy altered headers or body and wants to signal it is not the authoritative copy.',
    spec: 'RFC 9110 §15.3.4',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 204,
    reason: 'No Content',
    official: true,
    summary: 'The request succeeded but there is no content to send; the client should keep its current view.',
    causes: "Common after a successful PUT/PATCH/DELETE that has nothing meaningful to return in the body.",
    spec: 'RFC 9110 §15.3.5',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 205,
    reason: 'Reset Content',
    official: true,
    summary:
      'The request succeeded and the client should reset the document view that originated the request (e.g. clear a form).',
    causes: 'Used after form submissions to tell the browser to clear the form for new input.',
    spec: 'RFC 9110 §15.3.6',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 206,
    reason: 'Partial Content',
    official: true,
    summary: "The server is returning only part of the resource, as requested via a `Range` header.",
    causes: 'Byte-range requests: resumable downloads, or seeking within streamed media.',
    spec: 'RFC 9110 §15.3.7',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['Content-Range', 'Content-Length', 'ETag'],
  },
  {
    code: 207,
    reason: 'Multi-Status',
    official: true,
    summary:
      'Conveys multiple independent status codes for a single request, one per affected resource, in an XML body.',
    causes:
      'WebDAV operations that act on multiple resources at once (e.g. PROPFIND), each of which can succeed or fail independently.',
    spec: 'RFC 4918 §11.1',
    retryable: 'depends',
    retryNote: 'Retry only the sub-operations that failed.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 208,
    reason: 'Already Reported',
    official: true,
    summary:
      'Avoids re-listing a WebDAV binding member more than once within the same 207 Multi-Status response.',
    causes: 'The same resource was already enumerated once in this response via a different binding.',
    spec: 'RFC 5842 §7.1',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 226,
    reason: 'IM Used',
    official: true,
    summary:
      'The response is the result of applying one or more instance manipulations (e.g. a delta) to the current instance.',
    causes:
      'Used with delta encoding when the client asked for a diff via an `A-IM` header instead of the full resource.',
    spec: 'RFC 3229 §10.4.1',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['IM', 'Cache-Control'],
  },

  // ---------------------------------------------------------------- 3xx --
  {
    code: 300,
    reason: 'Multiple Choices',
    official: true,
    summary: 'The target resource has multiple representations and the client (or server) must pick one.',
    causes: 'Content-negotiation ambiguity, e.g. the same content is available in several formats at different URIs.',
    spec: 'RFC 9110 §15.4.1',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['Location'],
  },
  {
    code: 301,
    reason: 'Moved Permanently',
    official: true,
    summary: 'The resource has permanently moved to a new URI; future requests should use the new URI.',
    causes:
      'Permanent URL restructuring. Historically, clients may switch a POST to a GET on redirect — use 308 if the method/body must be preserved.',
    spec: 'RFC 9110 §15.4.2',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['Location'],
  },
  {
    code: 302,
    reason: 'Found',
    official: true,
    summary: 'The resource is temporarily at a different URI; the client should keep using the original URI in the future.',
    causes:
      "Temporary redirect where clients historically (and often still) switch the method to GET when following it — use 307 if that must not happen.",
    spec: 'RFC 9110 §15.4.3',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 303,
    reason: 'See Other',
    official: true,
    summary: 'The response to the request can be found at a different URI, to be retrieved with GET.',
    causes: 'The classic Post/Redirect/Get pattern: after a successful POST, send the browser to a GET-able result page.',
    spec: 'RFC 9110 §15.4.4',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 304,
    reason: 'Not Modified',
    official: true,
    summary: "The client's cached copy is still valid; no response body is sent.",
    causes: 'A conditional GET using `If-None-Match` / `If-Modified-Since` where the resource has not changed.',
    spec: 'RFC 9110 §15.4.5',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['ETag', 'Last-Modified', 'Cache-Control'],
  },
  {
    code: 305,
    reason: 'Use Proxy',
    official: true,
    summary: 'Deprecated: the requested resource must be accessed through the proxy given in `Location`.',
    causes: 'Effectively unused today; deprecated over security concerns. Do not use in new designs.',
    spec: 'RFC 9110 §15.4.6',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 306,
    reason: '(Unused)',
    official: true,
    summary: 'Reserved. Used by an early draft of the HTTP/1.1 spec and is not used by current HTTP.',
    causes: 'No current use — the number is reserved rather than reassigned.',
    spec: 'RFC 9110 §15.4.7',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 307,
    reason: 'Temporary Redirect',
    official: true,
    summary: 'Like 302, but guarantees the method and body are NOT changed when the client follows the redirect.',
    causes: 'A temporary redirect for a non-GET request (e.g. POST) where the method/body must be preserved exactly.',
    spec: 'RFC 9110 §15.4.8',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Location'],
  },
  {
    code: 308,
    reason: 'Permanent Redirect',
    official: true,
    summary: 'Like 301, but guarantees the method and body are NOT changed when the client follows the redirect.',
    causes: 'A permanent redirect where the method/body must be preserved exactly.',
    spec: 'RFC 7538 §3 (also RFC 9110 §15.4.9)',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['Location'],
  },

  // ---------------------------------------------------------------- 4xx --
  {
    code: 400,
    reason: 'Bad Request',
    official: true,
    summary: 'The server cannot process the request due to a client error, such as malformed request syntax.',
    causes: 'Malformed JSON, invalid query parameters, or a request the server cannot parse at all.',
    spec: 'RFC 9110 §15.5.1',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 401,
    reason: 'Unauthorized',
    official: true,
    summary: 'The request lacks valid authentication credentials for the target resource.',
    causes:
      "Missing, invalid, or expired credentials/token. Despite the name, this is about authentication, not authorization.",
    spec: 'RFC 9110 §15.5.2',
    retryable: 'depends',
    retryNote: 'Retry after supplying valid credentials.',
    cacheableByDefault: false,
    relatedHeaders: ['WWW-Authenticate'],
  },
  {
    code: 402,
    reason: 'Payment Required',
    official: true,
    summary: 'Reserved for future use; originally envisioned for digital payment schemes.',
    causes: 'Rarely used as specified; some APIs informally repurpose it for billing or quota-exceeded errors.',
    spec: 'RFC 9110 §15.5.3',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 403,
    reason: 'Forbidden',
    official: true,
    summary: 'The server understood the request but refuses to authorize it.',
    causes: 'The client is authenticated but lacks permission, or the server chooses not to reveal why access is denied.',
    spec: 'RFC 9110 §15.5.4',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 404,
    reason: 'Not Found',
    official: true,
    summary: "The server can't find the requested resource, or won't disclose that it exists.",
    causes: 'Wrong URL/ID, a deleted resource, or intentionally hiding existence for privacy or security.',
    spec: 'RFC 9110 §15.5.5',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 405,
    reason: 'Method Not Allowed',
    official: true,
    summary: "The method used isn't supported for this resource.",
    causes: 'E.g. sending POST to a read-only endpoint. The response should list the allowed methods.',
    spec: 'RFC 9110 §15.5.6',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: ['Allow'],
  },
  {
    code: 406,
    reason: 'Not Acceptable',
    official: true,
    summary: "No representation matching the client's `Accept` headers is available.",
    causes: "Content-negotiation failure — the server can't produce a response matching the requested media type/language/encoding.",
    spec: 'RFC 9110 §15.5.7',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Accept', 'Vary'],
  },
  {
    code: 407,
    reason: 'Proxy Authentication Required',
    official: true,
    summary: 'Like 401, but authentication is required by a proxy in the request chain.',
    causes: 'Missing or invalid credentials for an intermediary proxy.',
    spec: 'RFC 9110 §15.5.8',
    retryable: 'depends',
    retryNote: 'Retry after authenticating with the proxy.',
    cacheableByDefault: false,
    relatedHeaders: ['Proxy-Authenticate'],
  },
  {
    code: 408,
    reason: 'Request Timeout',
    official: true,
    summary: 'The server timed out waiting for the client to send the rest of the request.',
    causes: 'A slow or idle client connection; the server closes the connection after a timeout.',
    spec: 'RFC 9110 §15.5.9',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: ['Connection'],
  },
  {
    code: 409,
    reason: 'Conflict',
    official: true,
    summary: 'The request conflicts with the current state of the target resource.',
    causes: 'Concurrent edit conflicts, duplicate resource creation, or version mismatches.',
    spec: 'RFC 9110 §15.5.10',
    retryable: 'depends',
    retryNote: 'Retry after resolving the conflict (e.g. re-fetch and re-apply the change).',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 410,
    reason: 'Gone',
    official: true,
    summary: 'The resource used to exist but has been permanently removed, with no forwarding address known.',
    causes: 'Deliberate, permanent removal — a stronger signal than 404 that the resource will not come back.',
    spec: 'RFC 9110 §15.5.11',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 411,
    reason: 'Length Required',
    official: true,
    summary: 'The server requires a `Content-Length` header, which the request omitted.',
    causes: 'The server rejects unsized (e.g. chunked) request bodies where it needs the length upfront.',
    spec: 'RFC 9110 §15.5.12',
    retryable: 'depends',
    retryNote: 'Retry with `Content-Length` set.',
    cacheableByDefault: false,
    relatedHeaders: ['Content-Length'],
  },
  {
    code: 412,
    reason: 'Precondition Failed',
    official: true,
    summary: "One or more conditions in the request's conditional headers evaluated to false.",
    causes: '`If-Match` / `If-Unmodified-Since` / `If-None-Match` failed — commonly used for optimistic concurrency control.',
    spec: 'RFC 9110 §15.5.13',
    retryable: 'depends',
    retryNote: 'Retry after re-reading the current state and updating the precondition.',
    cacheableByDefault: false,
    relatedHeaders: ['If-Match', 'If-Unmodified-Since', 'If-None-Match'],
  },
  {
    code: 413,
    reason: 'Content Too Large',
    official: true,
    summary: 'The request body is larger than the server is willing or able to process.',
    causes: 'Large file uploads exceeding server or proxy body-size limits.',
    spec: 'RFC 9110 §15.5.14',
    retryable: 'depends',
    retryNote: 'Retry with a smaller payload, or later if the limit is temporary; the server may send `Retry-After`.',
    cacheableByDefault: false,
    relatedHeaders: ['Retry-After'],
  },
  {
    code: 414,
    reason: 'URI Too Long',
    official: true,
    summary: 'The request target (URL) is longer than the server is willing to interpret.',
    causes: 'Extremely long query strings, often from a client turning a large payload into a GET.',
    spec: 'RFC 9110 §15.5.15',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 415,
    reason: 'Unsupported Media Type',
    official: true,
    summary: "The payload's format is not supported by the server for this resource or method.",
    causes: 'Sending XML to a JSON-only endpoint, or a wrong/missing `Content-Type` header.',
    spec: 'RFC 9110 §15.5.16',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Content-Type', 'Accept'],
  },
  {
    code: 416,
    reason: 'Range Not Satisfiable',
    official: true,
    summary: "None of the ranges in the request's `Range` header overlap with the resource's actual size.",
    causes: 'Requesting a byte range beyond the end of the resource, e.g. resuming a download with a stale offset.',
    spec: 'RFC 9110 §15.5.17',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Content-Range'],
  },
  {
    code: 417,
    reason: 'Expectation Failed',
    official: true,
    summary: "The expectation given in the request's `Expect` header could not be met.",
    causes: "The client sent `Expect: 100-continue` (or another expectation) that the server can't satisfy.",
    spec: 'RFC 9110 §15.5.18',
    retryable: 'depends',
    retryNote: 'Retry without the `Expect` header.',
    cacheableByDefault: false,
    relatedHeaders: ['Expect'],
  },
  {
    code: 418,
    reason: "I'm a Teapot",
    official: true,
    summary: "An April Fools' joke status code; not part of serious HTTP semantics.",
    causes:
      'Originally from the Hyper Text Coffee Pot Control Protocol; some frameworks and APIs implement it as an easter egg.',
    spec: "RFC 2324 §2.3.2 (RFC 9110 Appendix B notes the code as unused)",
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 421,
    reason: 'Misdirected Request',
    official: true,
    summary: "The request was directed at a server that can't produce a response for this scheme/authority combination.",
    causes: 'A reused (e.g. HTTP/2) connection routed a request to the wrong virtual host or origin.',
    spec: 'RFC 9110 §15.5.19',
    retryable: 'yes',
    retryNote: 'Retry over a fresh connection to the correct origin.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 422,
    reason: 'Unprocessable Content',
    official: true,
    summary: 'The request was well-formed but contains semantic errors that prevent it from being processed.',
    causes: 'Failed business-rule/schema validation, e.g. a missing required field or an invalid enum value — the syntax was fine, the meaning was not.',
    spec: 'RFC 9110 §15.5.20 (originally RFC 4918 §11.2 as "Unprocessable Entity")',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 423,
    reason: 'Locked',
    official: true,
    summary: 'The source or destination resource of the request is locked.',
    causes: 'A WebDAV LOCK is held on the resource by another client or session.',
    spec: 'RFC 4918 §11.3',
    retryable: 'depends',
    retryNote: 'Retry after the lock is released.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 424,
    reason: 'Failed Dependency',
    official: true,
    summary: 'The request failed because it depended on another request that failed.',
    causes: 'Used in WebDAV method chains (e.g. a batched PROPPATCH) where one sub-operation failing cascades to the rest.',
    spec: 'RFC 4918 §11.4',
    retryable: 'depends',
    retryNote: 'Retry once the dependency it relied on succeeds.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 425,
    reason: 'Too Early',
    official: true,
    summary: 'The server is unwilling to risk processing a request that might be replayed.',
    causes: 'The request was sent as TLS 1.3 0-RTT "early data", which is replayable; the server defers non-idempotent requests until the handshake completes.',
    spec: 'RFC 8470 §5.2',
    retryable: 'yes',
    retryNote: 'Retry once the TLS handshake has completed (not as early data).',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 426,
    reason: 'Upgrade Required',
    official: true,
    summary: 'The server refuses to continue on the current protocol and requires the client to upgrade.',
    causes: 'The server requires TLS, HTTP/2, or another newer protocol before it will process the request.',
    spec: 'RFC 9110 §15.5.21',
    retryable: 'yes',
    retryNote: 'Retry after switching to the protocol named in `Upgrade`.',
    cacheableByDefault: false,
    relatedHeaders: ['Upgrade', 'Connection'],
  },
  {
    code: 428,
    reason: 'Precondition Required',
    official: true,
    summary: 'The origin server requires the request to be conditional (e.g. include `If-Match`).',
    causes: "Prevents the 'lost update' problem, where two clients update a resource without knowing about each other's changes.",
    spec: 'RFC 6585 §3',
    retryable: 'yes',
    retryNote: 'Retry with the required conditional header set.',
    cacheableByDefault: false,
    relatedHeaders: ['If-Match', 'If-Unmodified-Since'],
  },
  {
    code: 429,
    reason: 'Too Many Requests',
    official: true,
    summary: 'The client has sent too many requests in a given period (rate limiting).',
    causes: 'API rate limits or quota exceeded.',
    spec: 'RFC 6585 §4',
    retryable: 'yes',
    retryNote: 'Wait for the duration in `Retry-After` before retrying.',
    cacheableByDefault: false,
    relatedHeaders: ['Retry-After'],
  },
  {
    code: 431,
    reason: 'Request Header Fields Too Large',
    official: true,
    summary: "The request's header fields are too large for the server to process.",
    causes: 'Oversized cookies, excessively long headers, or too many headers.',
    spec: 'RFC 6585 §5',
    retryable: 'depends',
    retryNote: 'Retry with smaller/fewer headers.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 451,
    reason: 'Unavailable For Legal Reasons',
    official: true,
    summary: 'The resource is unavailable due to a legal demand, such as censorship or a court order.',
    causes: 'Government or legal takedown requests blocking access to specific content.',
    spec: 'RFC 7725 §3',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: ['Link'],
  },

  // ---------------------------------------------------------------- 5xx --
  {
    code: 500,
    reason: 'Internal Server Error',
    official: true,
    summary: 'A generic, unexpected condition on the server prevented it from fulfilling the request.',
    causes: 'Unhandled exceptions or bugs in server-side code.',
    spec: 'RFC 9110 §15.6.1',
    retryable: 'depends',
    retryNote: 'Safe to retry idempotent requests; the bug may or may not be transient.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 501,
    reason: 'Not Implemented',
    official: true,
    summary: "The server doesn't support the functionality required to fulfill the request.",
    causes: 'An unrecognized/unsupported method, or a feature that has not been built yet.',
    spec: 'RFC 9110 §15.6.2',
    retryable: 'no',
    cacheableByDefault: true,
    relatedHeaders: [],
  },
  {
    code: 502,
    reason: 'Bad Gateway',
    official: true,
    summary: 'A server acting as a gateway or proxy received an invalid response from the upstream server.',
    causes: 'The upstream service crashed, returned malformed data, or reset the connection.',
    spec: 'RFC 9110 §15.6.3',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 503,
    reason: 'Service Unavailable',
    official: true,
    summary: 'The server is temporarily unable to handle the request, e.g. due to overload or maintenance.',
    causes: 'Deployments/maintenance windows, capacity limits, or a circuit breaker tripping.',
    spec: 'RFC 9110 §15.6.4',
    retryable: 'yes',
    retryNote: 'Wait for the duration in `Retry-After` if present, then retry.',
    cacheableByDefault: false,
    relatedHeaders: ['Retry-After'],
  },
  {
    code: 504,
    reason: 'Gateway Timeout',
    official: true,
    summary: "A server acting as a gateway or proxy didn't receive a timely response from the upstream server.",
    causes: 'A slow or hung upstream/backend service.',
    spec: 'RFC 9110 §15.6.5',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 505,
    reason: 'HTTP Version Not Supported',
    official: true,
    summary: "The server doesn't support the HTTP protocol version used in the request.",
    causes: 'The client used an obsolete or unsupported HTTP version.',
    spec: 'RFC 9110 §15.6.6',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 506,
    reason: 'Variant Also Negotiates',
    official: true,
    summary:
      'A server-side configuration error: the chosen variant resource is itself configured to engage in content negotiation, creating a loop.',
    causes: 'Misconfigured transparent content negotiation (RFC 2295).',
    spec: 'RFC 2295 §8.1',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 507,
    reason: 'Insufficient Storage',
    official: true,
    summary: "The server can't store the representation needed to complete the request.",
    causes: 'The server ran out of disk space or quota while processing the request.',
    spec: 'RFC 4918 §11.5',
    retryable: 'depends',
    retryNote: 'Retry once storage is freed up.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 508,
    reason: 'Loop Detected',
    official: true,
    summary: 'The server detected an infinite loop while processing the request.',
    causes: 'Circular references in WebDAV bindings, e.g. a collection that contains itself.',
    spec: 'RFC 5842 §7.2',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 510,
    reason: 'Not Extended',
    official: true,
    summary: 'Further extensions to the request are required for the server to fulfill it.',
    causes: 'The server requires an HTTP extension policy (RFC 2774) that the request did not include.',
    spec: 'RFC 2774 §7',
    retryable: 'depends',
    retryNote: 'Retry with the required extension declared.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 511,
    reason: 'Network Authentication Required',
    official: true,
    summary: 'The client needs to authenticate to gain network access, e.g. behind a captive portal.',
    causes: 'Public Wi-Fi or captive portals intercepting traffic until the user logs in.',
    spec: 'RFC 6585 §6',
    retryable: 'yes',
    retryNote: 'Retry after completing the network login.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },

  // -------------------------------------------------- Unofficial/common --
  {
    code: 419,
    reason: 'Page Expired',
    official: false,
    summary: 'Unofficial (Laravel): the CSRF/session token used for the request has expired.',
    causes: 'A form was submitted after the session or CSRF token had expired.',
    spec: 'No RFC — framework-specific (Laravel)',
    retryable: 'depends',
    retryNote: 'Retry after refreshing the page/token.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 420,
    reason: 'Enhance Your Calm',
    official: false,
    summary: 'Unofficial (legacy Twitter API): the client is being rate-limited.',
    causes: 'Used historically by the Twitter API; conceptually equivalent to 429.',
    spec: 'No RFC — used historically by the Twitter API',
    retryable: 'yes',
    retryNote: 'Wait for the duration in `Retry-After` if present, then retry.',
    cacheableByDefault: false,
    relatedHeaders: ['Retry-After'],
  },
  {
    code: 444,
    reason: 'No Response',
    official: false,
    summary: 'Unofficial (nginx): the server closed the connection without sending any response.',
    causes: 'nginx uses this internally (it is never actually sent on the wire) to log requests it deliberately dropped, e.g. from malformed or malicious clients.',
    spec: 'No RFC — nginx-specific',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 499,
    reason: 'Client Closed Request',
    official: false,
    summary: 'Unofficial (nginx): the client closed the connection before the server could send a response.',
    causes: 'A client-side timeout, or the user navigating away while a slow request was still in flight.',
    spec: 'No RFC — nginx-specific',
    retryable: 'depends',
    retryNote: "Retry if the client's own timeout was too aggressive.",
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 520,
    reason: 'Web Server Returned an Unknown Error',
    official: false,
    summary: 'Unofficial (Cloudflare): the origin server returned an unrecognized or empty response.',
    causes: 'The origin crashed, returned an empty response, or violated the HTTP spec in a way Cloudflare could not parse.',
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 521,
    reason: 'Web Server Is Down',
    official: false,
    summary: 'Unofficial (Cloudflare): the origin server refused the connection.',
    causes: 'The origin server is down or is actively refusing connections from Cloudflare.',
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 522,
    reason: 'Connection Timed Out',
    official: false,
    summary: 'Unofficial (Cloudflare): Cloudflare could not complete a TCP handshake with the origin.',
    causes: 'The origin server is unreachable, or there is a network/firewall issue between Cloudflare and the origin.',
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 523,
    reason: 'Origin Is Unreachable',
    official: false,
    summary: "Unofficial (Cloudflare): Cloudflare could not reach the origin server (routing issue).",
    causes: 'A DNS or routing failure to the origin, or the origin is offline.',
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 524,
    reason: 'A Timeout Occurred',
    official: false,
    summary: 'Unofficial (Cloudflare): Cloudflare connected to the origin but the connection timed out before a response completed.',
    causes: "The origin is too slow to respond within Cloudflare's timeout window.",
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 525,
    reason: 'SSL Handshake Failed',
    official: false,
    summary: 'Unofficial (Cloudflare): the SSL/TLS handshake between Cloudflare and the origin failed.',
    causes: "The origin's TLS configuration is invalid or incompatible.",
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'depends',
    retryNote: 'Retry after fixing the origin TLS configuration.',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 526,
    reason: 'Invalid SSL Certificate',
    official: false,
    summary: "Unofficial (Cloudflare): the origin's SSL certificate is invalid or could not be validated.",
    causes: 'An expired, self-signed, or mismatched origin TLS certificate.',
    spec: 'No RFC — Cloudflare-specific',
    retryable: 'no',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 527,
    reason: 'Railgun Error',
    official: false,
    summary: "Unofficial (Cloudflare): the connection between Cloudflare and its (now-deprecated) Railgun host failed.",
    causes: "Cloudflare's deprecated Railgun feature; the connection between Cloudflare and Railgun timed out.",
    spec: 'No RFC — Cloudflare-specific (Railgun is deprecated)',
    retryable: 'depends',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 598,
    reason: 'Network Read Timeout Error',
    official: false,
    summary: 'Unofficial: an informal convention used by some HTTP proxies to report a read timeout from the upstream server.',
    causes: 'A proxy or gateway timed out reading a response from the upstream server.',
    spec: 'No RFC — informal proxy convention',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
  {
    code: 599,
    reason: 'Network Connect Timeout Error',
    official: false,
    summary: 'Unofficial: an informal convention used by some HTTP proxies/clients to report a connect timeout.',
    causes: 'A proxy or client timed out establishing a TCP connection to the upstream server.',
    spec: 'No RFC — informal proxy convention',
    retryable: 'yes',
    cacheableByDefault: false,
    relatedHeaders: [],
  },
];

export const STATUS_CODES: StatusCodeEntry[] = RAW_ENTRIES.map((entry) => ({
  ...entry,
  statusClass: classOf(entry.code),
})).sort((a, b) => a.code - b.code);

export const STATUS_BY_CODE: Map<number, StatusCodeEntry> = new Map(
  STATUS_CODES.map((entry) => [entry.code, entry]),
);

export const STATUS_CLASSES: StatusClass[] = ['1xx', '2xx', '3xx', '4xx', '5xx'];

export const STATUS_CLASS_LABELS: Record<StatusClass, string> = {
  '1xx': 'Informational',
  '2xx': 'Success',
  '3xx': 'Redirection',
  '4xx': 'Client Error',
  '5xx': 'Server Error',
};
